---
all:
  children:
    kafka_brokers:
      children:
        dc1:
          hosts:
            dc1-broker1:
              ansible_host: 10.1.0.11
              broker_id: 1
            dc1-broker2:
              ansible_host: 10.1.0.12
              broker_id: 2
            dc1-broker3:
              ansible_host: 10.1.0.13
              broker_id: 3
          vars:
            rack: dc1
            dc_index: 1

        dc2:
          hosts:
            dc2-broker1:
              ansible_host: 10.2.0.11
              broker_id: 4
            dc2-broker2:
              ansible_host: 10.2.0.12
              broker_id: 5
            dc2-broker3:
              ansible_host: 10.2.0.13
              broker_id: 6
          vars:
            rack: dc2
            dc_index: 2

        dc3:
          hosts:
            dc3-broker1:
              ansible_host: 10.3.0.11
              broker_id: 7
            dc3-broker2:
              ansible_host: 10.3.0.12
              broker_id: 8
            dc3-broker3:
              ansible_host: 10.3.0.13
              broker_id: 9
          vars:
            rack: dc3
            dc_index: 3

    kafka_connect:
      hosts:
        dc1-connect1:
          ansible_host: 10.1.0.21
        dc2-connect1:
          ansible_host: 10.2.0.21
        dc3-connect1:
          ansible_host: 10.3.0.21

    emqx:
      children:
        emqx_dc1:
          hosts:
            dc1-emqx1:
              ansible_host: 10.1.0.31
            dc1-emqx2:
              ansible_host: 10.1.0.32
            dc1-emqx3:
              ansible_host: 10.1.0.33
          vars:
            rack: dc1
        emqx_dc2:
          hosts:
            dc2-emqx1:
              ansible_host: 10.2.0.31
            dc2-emqx2:
              ansible_host: 10.2.0.32
            dc2-emqx3:
              ansible_host: 10.2.0.33
          vars:
            rack: dc2
        emqx_dc3:
          hosts:
            dc3-emqx1:
              ansible_host: 10.3.0.31
            dc3-emqx2:
              ansible_host: 10.3.0.32
            dc3-emqx3:
              ansible_host: 10.3.0.33
          vars:
            rack: dc3
